use_frameworks!

platform :ios, '8.0'

target 'LCAlertController_Example' do
  pod 'LCAlertController', :path => '../'

  target 'LCAlertController_Tests' do
    inherit! :search_paths

    
  end
end
